version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_HOST: '%'  
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - rapidinner_data:/var/lib/mysql  

volumes:
  rapidinner_data: