POST http://localhost:8080/users      -> Criar Usuario
GET http://localhost:8080/users       -> Listar Todos Usuarios
GET http://localhost:8080/users/id    -> Busca Usuario por Id
PUT http://localhost:8080/users/id    -> Atualizar por Id
DELETE http://localhost:8080/users/id -> Deletar por Id


Criar ADMIN
{
    "name": "Carlos Admin",
    "email": "carlos@empresa.com",
    "role": "ROLE_ADMIN",
    "active": true
}

Criar DELIVERYMAN
{
    "name": "Maria Entregadora",
    "email": "maria@entregas.com",
    "role": "ROLE_DELIVERYMAN",
    "cnh": "123456789",
    "rating": 4.8,
    "available": true,
    "vehicle": {
        "type": "Moto",
        "color": "Preta",
        "model": "Yamaha YBR 150",
        "plate": "XYZ-9876"
    }
}

Criar CUSTOMER
{
    "name": "Maria CCC",
    "email": "maria@CCC.com",
    "role": "ROLE_CUSTOMER",
    "cpf": "123.456.789-12",
    "addresses": {
        "HOME": {
            "street": "wee",
            "city": "Bahia",
            "state": "BA",
            "number": "1234",
            "zipCode": "01234-144",
            "country": "Brasil",
            "primary": true,
            "complement": null,
            "referencePoint": null
        }
    }
}

Criar MERCHANT
  {
    "name": "Loja Teste2",
    "email": "contato@loja2xpto.com",
    "role": "ROLE_MERCHANT",
    "cnpj": "12345678000188",
    "businessAddress": {
        "street": "Rua das Lojas2",
        "city": "São Paulo",
        "state": "SP",
        "number": "1243",
        "zipCode": "01001-000",
        "country": "Brasil",
        "primary": true,
        "complement": "Loja 2",
        "referencePoint": "Próximo ao shopping"
    },
    "companyName": "Loj2a XPTO2 LTDA2"
}

Atualizar User 
{
    "name": "MarcossLoja",
    "email": "contato@loja2xpto.com",
    "role": "ROLE_MERCHANT",
    "cnpj": "12345678000144",
    "businessAddress": {
        "street": "Rua das Lojas2",
        "city": "São Paulo",
        "state": "SP",
        "number": "1243",
        "zipCode": "01001-000",
        "country": "Brasil",
        "primary": true,
        "complement": "Loja 2",
        "referencePoint": "Próximo ao shopping"
    },
    "companyName": "MiFour"
}